<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DOCTYPE</name>
   <tag></tag>
   <elementGuidId>5aacf2b5-60eb-4d56-a473-aa0e9cc3e21a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leftmenuinnerinner > div.notranslate > a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2dce414f-9926-42da-85e3-d714238d2fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>dcbdc8ef-27ce-4882-a799-a0039c1c76bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>tag_doctype.asp</value>
      <webElementGuid>e37094b8-0d25-4e37-8345-aa4a7e54f19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;!DOCTYPE></value>
      <webElementGuid>cd1e1b69-cb97-4dbe-81b9-d3fb99fd89fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/div[@class=&quot;notranslate&quot;]/a[2]</value>
      <webElementGuid>0c160869-dad1-48c7-a1ca-c97eed916e9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/div/a[2]</value>
      <webElementGuid>b6169a16-08e6-4abe-8839-86a129557e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'&lt;!DOCTYPE>')]</value>
      <webElementGuid>51032fd5-3c6d-4d43-a488-361cd526ff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;!-->'])[1]/following::a[1]</value>
      <webElementGuid>4ff39582-eab2-4635-8e7d-0dbc12d0e82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[5]/following::a[2]</value>
      <webElementGuid>81919398-c66f-4a07-89c1-7ed47706a6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;a>'])[1]/preceding::a[1]</value>
      <webElementGuid>5a303ad3-3796-445e-ac1a-8385a4382cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;abbr>'])[1]/preceding::a[2]</value>
      <webElementGuid>213ef7c9-a891-48dc-8529-a0d967b3c597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;!DOCTYPE>']/parent::*</value>
      <webElementGuid>babc32ce-6e73-48eb-ac52-fd428e37d285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'tag_doctype.asp')]</value>
      <webElementGuid>d1f4c39a-069b-446e-b10f-b34552bb2199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a[2]</value>
      <webElementGuid>532ec0dc-6817-4b7f-a5e1-31993d393fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'tag_doctype.asp' and (text() = '&lt;!DOCTYPE>' or . = '&lt;!DOCTYPE>')]</value>
      <webElementGuid>ecfc3c0a-840b-4a3b-ab20-3485250f63d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
