<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HTML by Alphabet</name>
   <tag></tag>
   <elementGuidId>371fa59e-7962-42d7-850e-6b04445baa6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leftmenuinnerinner > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftmenuinnerinner']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6fd10320-c7e8-48ee-ad9c-442703cd1d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>6cd2741b-c6b4-4053-b8bf-01f230ab47e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>default.asp</value>
      <webElementGuid>8f1cfbcb-ce98-4875-b047-728cb5227267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTML by Alphabet</value>
      <webElementGuid>25286096-b939-494f-a4a0-eac3d43180d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftmenuinnerinner&quot;)/a[1]</value>
      <webElementGuid>60d5eba8-9d80-4e6e-ae9f-4ae78362b69c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftmenuinnerinner']/a</value>
      <webElementGuid>2970d0ad-88ad-4866-99c7-d9236157d6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HTML by Alphabet')]</value>
      <webElementGuid>8d8ed61d-60a3-4993-bdbc-232e4419e7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[4]/following::a[1]</value>
      <webElementGuid>b30f5ce3-b936-4675-9a7b-920f239d0fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML by Category'])[1]/preceding::a[1]</value>
      <webElementGuid>944ac22d-513c-4ddd-97ca-08ba142fdd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML Browser Support'])[1]/preceding::a[2]</value>
      <webElementGuid>4f2c0db7-a7bf-4ad3-b2f7-5bc90ac8d35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HTML by Alphabet']/parent::*</value>
      <webElementGuid>589eefb7-9576-419e-b3a2-524dd14427d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'default.asp')])[112]</value>
      <webElementGuid>27b19c91-a5e7-44af-8c20-42d458f5c078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>9fb38f78-92f5-4159-a296-99b6d0414de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'default.asp' and (text() = 'HTML by Alphabet' or . = 'HTML by Alphabet')]</value>
      <webElementGuid>61bc8a1a-37a6-4239-bac8-3bc011ee105b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
