<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tutorials filter input_filter-tutoria_e71851</name>
   <tag></tag>
   <elementGuidId>d559334f-3f43-4508-92ed-22f5c2c4be47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-tutorials-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-tutorials-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a8beb93-5d52-45ff-a1a7-1d3d2f1f1b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-tutorials-input</value>
      <webElementGuid>5f6d5f28-559a-4e31-91d1-e4c65c3a2f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_tutorials')</value>
      <webElementGuid>4a24bfa6-06d8-4b1c-9d20-c03c83bd643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45e68ff7-f8ab-46d3-ba03-6274a57ba38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>bf6c93eb-9b28-4f64-9aea-48a9a2c7a043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>f881bdda-4d61-4fa0-ba5c-c27d2c3acd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tutorials filter input</value>
      <webElementGuid>287cca53-8694-4cf1-8722-170d90e0036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-tutorials-input&quot;)</value>
      <webElementGuid>05509809-e239-4bce-bdc1-e651ef118d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-tutorials-input']</value>
      <webElementGuid>0ada0dbd-b047-4345-bb05-0b0238e216fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tutorials_list']/div/div[2]/div/input</value>
      <webElementGuid>4d5cf022-6998-4705-876a-15922f0bc5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b00c23e1-ead5-4fd0-88f6-df05ddcb7e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-tutorials-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>640d3a87-e05c-4630-8687-309c566cc0b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
