<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter field for certifications_filte_73e64a</name>
   <tag></tag>
   <elementGuidId>75e1601f-60b6-4bf1-a96b-46387cb4c1f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-certified-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-certified-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78aad623-bee9-4f84-bd88-17f5bab07c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-certified-input</value>
      <webElementGuid>37ab63b8-3691-4f4f-a0fa-97480bf26d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.filter(event, 'nav_certified')</value>
      <webElementGuid>b7abb649-879c-4f7e-ad28-284ebefd2516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3c6eb1e-aefb-4af6-b749-deb5af4e0cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-input</value>
      <webElementGuid>39c85646-9758-448c-840d-63d4526fa9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter...</value>
      <webElementGuid>31b3d870-dc52-4c35-bd2b-17ad6bef2bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Certificate filter bar</value>
      <webElementGuid>d6539594-6ce6-4884-a666-89b7a9d871da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-certified-input&quot;)</value>
      <webElementGuid>2d37ddcd-9534-40dc-bc9c-15acb8bb709c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-certified-input']</value>
      <webElementGuid>45861316-2f42-4374-9809-6b1a426aeb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='certified_list']/div/div[2]/div/input</value>
      <webElementGuid>71b4893d-ed14-4cc9-b0bf-f74a8c2d21ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>4f5d4cc7-ffb9-4052-afc0-0317af21e3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-certified-input' and @type = 'text' and @placeholder = 'Filter...']</value>
      <webElementGuid>92d45aec-f7e0-4c76-ac00-af8631ec9b9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
